"""add_profile_info_table

Revision ID: 4ad289092727
Revises: 976136ebd876
Create Date: 2026-01-06 16:52:16.424516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad289092727'
down_revision: Union[str, Sequence[str], None] = '976136ebd876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('running_goal', sa.String(length=255), nullable=True),
    sa.Column('has_injuries', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('uq_users_google_sub'), 'users', type_='unique')
    op.drop_column('users', 'google_sub')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(length=32), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('google_sub', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_users_google_sub'), 'users', ['google_sub'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('profiles')
    # ### end Alembic commands ###
